#define IDR_ICONS   101

#define VERSION_WORDS    1,3,9,5
#define VERSION_TAGLEET "1.3.9.5"

#ifndef IDC_STATIC
#define IDC_STATIC  -1
#endif

#define IDD_SETTINGS 2600

#define IDB_OK                 (IDD_SETTINGS + 1)

#define IDC_CHK_NPPCOLORS      (IDD_SETTINGS + 2)
#define IDC_CHK_NPPAUTOC       (IDD_SETTINGS + 3)
#define IDC_CHK_UPDSAVE        (IDD_SETTINGS + 4)
#define IDC_CHK_RECURSIVE      (IDD_SETTINGS + 5)
#define IDC_EDT_PEEKPRE        (IDD_SETTINGS + 6)
#define IDC_EDT_PEEKPOST       (IDD_SETTINGS + 7)
#define IDC_EDT_GLOBALTAGSFILE (IDD_SETTINGS + 8)
#define IDC_BTN_GLOBALTAGSFILE (IDD_SETTINGS + 9)

#define IDC_STC_VER            (IDD_SETTINGS + 10)
